printctl script mostly fleshed out

diff --git a/scripts/util/printctl b/scripts/util/printctl
--- a/scripts/util/printctl
+++ b/scripts/util/printctl
@@ -1,26 +1,88 @@
 #!/bin/sh
 #
 # Helper script for connecting printers
-# TODO: Fix eval command
+#
+# TODO: sel_existing() does not validate
+# case where user exits dmenu via ESC
 
 source "$HOME/scripts/res/loadres"
 CACHE="printers"
 CACHE_PATH="$SCRIPT_RES/$RES_SUBDIR/$CACHE"
 
-if [ -f "$CACHE_PATH" ]
-then
-   PNAME=$(cat "$CACHE_PATH" | dmenu -p "Printers" -l 15 \
-   -g 1 -nb "#222222" -nf "#bbbbbb" -sb "#005577" -sf "#eeeeee")
-else
+add_new() {
+   # Parse IP address
    while
       echo "Enter IP address (xxx.xxx.xxx.xxx): " && read -r IP
-      echo "$IP" | grep -P "(\d{3})((\.\d{3}){3})" > /dev/null
+      echo "$IP" | grep -P "(\d{3})((\.\d{3}){3})" &> /dev/null
       (("$?" != "0"))
    do :; done
-   echo "Enter printer's name: " && read -r PNAME
-   echo "$PNAME $IP" > "$CACHE_PATH"
-fi
 
+   # Parse printer name
+   while
+      echo "Enter printer's name: " && read -r PNAME
+      echo "$PNAME" | grep "\s\|^\$" &> /dev/null
+      [ "$?" == "0" ]
+   do :; done
+
+   # Append printer to cache (if it doesn't already exist)
+   grep "$PNAME $IP" "$CACHE_PATH" &> /dev/null
+   [ "$?" != "0" ] && echo "$PNAME $IP" >> "$CACHE_PATH"
+}
+
+sel_existing() {
+   # Open dmenu prompt with list of cached printers
+   PNAME=$(cat "$CACHE_PATH" | dmenu -p "Printers" -l 15 \
+   -g 1 -nb "#222222" -nf "#bbbbbb" -sb "#005577" -sf "#eeeeee")
+
+   # Parse selection
+   IP=$(echo "$PNAME" | awk '{print $2}')
+   PNAME=$(echo "$PNAME" | awk '{print $1}')
+}
+
+del_cache() {
+   echo "Are you sure you'd like to delete the printer cache? [y/n]" \
+   && read OPT
+   [ "$OPT" = "y" ] || [ "$OPT" = "Y" ] && rm "$CACHE_PATH" && exit 0 || menu
+}
+
+menu() {
+   if [ -f "$CACHE_PATH" ]; then
+      while
+         printf "%s\n%s\n%s\n" \
+         "1) Create new printer" \
+         "2) Use existing printer" \
+         "3) Clear printer cache" \
+         && read -r OPT
+         [ "$OPT" != "1" ] && \
+         [ "$OPT" != "2" ] && \
+         [ "$OPT" != "3" ]
+      do :; done
+
+      # Switch on user selection
+      case "$OPT" in
+         "1")
+            add_new
+            ;;
+         "2")
+            sel_existing
+            ;;
+         "3")
+            del_cache
+            ;;
+         *)
+            # Should not reach!!!
+            echo "Invalid option" && exit 1
+            ;;
+         esac
+   else
+      add_new
+   fi
+}
+
+# Script start
+menu
+
+# Execute command
 CMD="lpadmin -p $PNAME -E -v ipp://$IP/ipp/print -m everywhere"
 echo "$CMD"
 eval "$CMD"
