Cleanup and script updates

diff --git a/devel/scripts/util/bt b/devel/scripts/util/bt
--- a/devel/scripts/util/bt
+++ b/devel/scripts/util/bt
@@ -42,23 +42,24 @@ SELECTION="$1"
 MAC="$(bluetoothctl devices | grep "Bose QC35 II" | awk '{print $2}')"
 
 signal_handler() {
-    PAIR_STAT="$(bluetoothctl info "$MAC" | sed '9q;d' | awk '{print $2}')"
-    [ "$PAIR_STAT" = "yes" ] && echo "Successfully paired with $MAC!" || echo "Failed to pair with $MAC..."
-    kill -TERM -$$
+    PAIRING_STATUS="$(bluetoothctl info "$MAC" | sed '9q;d' | awk '{print $2}')"
+    [ "$PAIRING_STATUS" = "yes" ] && echo "Successfully paired with $MAC!" || echo "Failed to pair with $MAC..."
+    exit 0
+}
+
+usage() {
+    printf "%s\n%s\n%s\n" \
+        "Options:" \
+        "on)    Attempts to connect with headphones" \
+        "off)   Terminates connection between headphones and bluetooth dongle"
 }
 
 turnon() {
-    trap signal_handler INT
+    trap signal_handler SIGINT
 
     echo "Please wait until headphones are in pairing mode and then run this script"
     bluetoothctl power on
     bluetoothctl connect "$MAC"
-
-    # Wait for interrupt signal (Ctrl+C)
-    for i in $(seq 1 100); do
-        sleep 1 &
-    done
-
     wait
 }
 
@@ -77,9 +78,6 @@ case "$SELECTION" in
         turnoff
         ;;
     *)
-        printf "%s\n%s\n%s\n" \
-            "Options:" \
-            "on)    Attempts to connect with headphones" \
-            "off)   Terminates connection between headphones and bluetooth dongle"
+        usage
         ;;
 esac
