Fixed machine selection

diff --git a/.config/vim/viminfo b/.config/vim/viminfo
--- a/.config/vim/viminfo
+++ b/.config/vim/viminfo
@@ -10,22 +10,96 @@
 
 # hlsearch on (H) or off (h):
 ~h
+# Last Search Pattern:
+~MSle0~/pkg
+
+# Last Substitute Search Pattern:
+~MSle0& 
+
 # Last Substitute String:
 $
 
 # Command Line History (newest to oldest):
-:q
-|2,0,1653522268,,"q"
 :wq
-|2,0,1653521563,,"wq"
-:q!
-|2,0,1653009134,,"q!"
+|2,0,1654464458,,"wq"
+:q
+|2,0,1654464444,,"q"
+:56
+|2,0,1654464361,,"56"
+:30
+|2,0,1654464352,,"30"
 :w
-|2,0,1652997769,,"w"
+|2,0,1654464331,,"w"
+:q!
+|2,0,1654462576,,"q!"
+:78
+|2,0,1654461129,,"78"
+:70
+|2,0,1654461107,,"70"
+:32
+|2,0,1654459586,,"32"
+:e ../includes/common.h
+|2,0,1654353715,,"e ../includes/common.h"
+:vsplit
+|2,0,1654353705,,"vsplit"
+:e
+|2,0,1654353702,,"e"
+:e error.c
+|2,0,1654353494,,"e error.c"
+:% s/ /&nbsp;/g
+|2,0,1654302531,,"% s/ /&nbsp;/g"
+:% s/ /&#x02fd;/g
+|2,0,1654298674,,"% s/ /&#x02fd;/g"
+:326
+|2,0,1653613436,,"326"
 
 # Search String History (newest to oldest):
 ? \s\+$
-|2,1,1653521563,,"\\s\\+$"
+|2,1,1654464458,,"\\s\\+$"
+?/sed
+|2,1,1654462400,47,"sed"
+?/pkg
+|2,1,1654460709,47,"pkg"
+?/$$
+|2,1,1654458923,47,"$$"
+?/scli
+|2,1,1654446447,47,"scli"
+?/EDITOR
+|2,1,1654446415,47,"EDITOR"
+?/wrap
+|2,1,1654396063,47,"wrap"
+?/INPUT
+|2,1,1654355463,47,"INPUT"
+?/ \__,_|___/\___|
+|2,1,1654352765,47," \\__,_|___/\\___|"
+?/ _` / __|/ __|
+|2,1,1654352763,47," _` / __|/ __|"
+?/current
+|2,1,1654308409,47,"current"
+?/working
+|2,1,1654308403,47,"working"
+?/DIRECTORY
+|2,1,1654308351,47,"DIRECTORY"
+?/OUTPUT
+|2,1,1654308349,47,"OUTPUT"
+?/foo
+|2,1,1654303154,47,"foo"
+?  
+|2,1,1654302531,," "
+?/ |_
+|2,1,1654302490,47," |_"
+?/ _` |/ _ \ __|
+|2,1,1654302490,47," _` |/ _ \\ __|"
+? @$
+|2,1,1654224489,,"@$"
+?/JAVADOC_AUTOBRIEF
+|2,1,1654223333,47,"JAVADOC_AUTOBRIEF"
+?/JComboBox
+|2,1,1653613454,47,"JComboBox"
+?/rstudio
+|2,1,1653611675,47,"rstudio"
+?/load_config
+|2,1,1653527256,47,"load_config"
 ?/read
 |2,1,1652997021,47,"read"
 
@@ -36,181 +110,219 @@ $
 # Debug Line History (newest to oldest):
 
 # Registers:
-"0	LINE	0
-	######################################################################
-|3,0,0,1,1,0,1630291676,"######################################################################"
-""1	BLOCK	1
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-	~/
-|3,1,1,2,21,1,1653103159,"~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/","~/"
+"0	CHAR	0
+	 | tr " " "\n"
+|3,0,0,0,1,0,1654461703," | tr \" \" \"\\n\""
+""1	LINE	0
+	   echo "$CHOICES" > file.log
+|3,1,1,1,1,0,1654464452,"   echo \"$CHOICES\" > file.log"
 "2	LINE	0
-	rm "$HOME/neil/.fehbg" &
-|3,0,2,1,1,0,1653010780,"rm \"$HOME/neil/.fehbg\" &"
+	   # Seems to break
+|3,0,2,1,1,0,1654464165,"   # Seems to break"
 "3	LINE	0
 	
-|3,0,3,1,1,0,1653009781,""
+|3,0,3,1,1,0,1654461766,""
 "4	LINE	0
-	#!/bin/sh
-|3,0,4,1,1,0,1653009781,"#!/bin/sh"
+	
+|3,0,4,1,1,0,1654461729,""
 "5	LINE	0
 	
-|3,0,5,1,1,0,1653007166,""
+|3,0,5,1,1,0,1654461729,""
 "6	LINE	0
-	fi
-|3,0,6,1,1,0,1653007165,"fi"
+	   for PC in $CHOICES
+	   do
+	      i=$((i+1))
+	      set -- "$@" $(echo $PC | awk '{print $1}')
+	      echo "[$i] $PC"
+	   done
+|3,0,6,1,6,0,1654461724,"   for PC in $CHOICES","   do","      i=$((i+1))","      set -- \"$@\" $(echo $PC | awk '{print $1}')","      echo \"[$i] $PC\"","   done"
 "7	LINE	0
-	   xrdb -merge $sysresources
-|3,0,7,1,1,0,1653007165,"   xrdb -merge $sysresources"
+	   echo "Please select the desired machine: "; read -r SELECTION
+|3,0,7,1,1,0,1654461722,"   echo \"Please select the desired machine: \"; read -r SELECTION"
 "8	LINE	0
-	if [ -f $sysresources ]; then
-|3,0,8,1,1,0,1653007164,"if [ -f $sysresources ]; then"
+	
+|3,0,8,1,1,0,1654461020,""
 "9	LINE	0
-	#Start xrdb (X Resource Database)
-|3,0,9,1,1,0,1653007164,"#Start xrdb (X Resource Database)"
+	check_machine()
+	{
+	   echo "Would you like to select which machine to use (usually required for arm/aarch64)?"
+	   echo "[y/n]"
+	   read -r SELECTION
+	   [ $SELECTION = y ] && select_machine()
+	   [ $SELECTION = n ] && select_hardware_accelerator() || echo "Invalid selection" && check_machine()
+	}
+	
+|3,0,9,1,9,0,1654460395,"check_machine()","{","   echo \"Would you like to select which machine to use (usually required for arm/aarch64)?\"","   echo \"[y/n]\"","   read -r SELECTION","   [ $SELECTION = y ] && select_machine()","   [ $SELECTION = n ] && select_hardware_accelerator() || echo \"Invalid selection\" && check_machine()","}",""
+"j	CHAR	0
+	jjkkkkjjkkkkkkkkjjjjIset kjlllkjA€kb€kb€kb€kb€kb€kb€kb€kb€kb == €kb€kb€kb-- "@"€kl€kl$€kr€kr $ikj€ýa
+|3,0,19,0,1,0,1654458251,"jjkkkkjjkkkkkkkkjjjjIset kjlllkjA€kb€kb€kb€kb€kb€kb€kb€kb€kb == €kb€kb€kb-- \"@\"€kl€kl$€kr€kr $ikj€ýa"
+"k	CHAR	0
+	kkkkjjjjjlkkjllllllllllllllllli"llllllllli"kkkkkkkkkkkkkkkjjjjjjjjjjkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkhhhhhhhhhhhhi"ji"hhhhhhhhhhhli"ki"kkkkkkkkkk:w s
+|3,0,20,0,1,0,1654464351,"kkkkjjjjjlkkjllllllllllllllllli\"llllllllli\"kkkkkkkkkkkkkkkjjjjjjjjjjkkkkkkkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkhhhhhhhhhhhhi\"ji\"hhhhhhhhhhhli\"ki\"kkkkkkkkkk:w s"
+"p	LINE	0
+	 * @param[in] dims_p Pointer to a dimensions struct
+	 * @param[in] page_p Pointer to a page struct
+|3,0,25,1,2,0,1654306295," * @param[in] dims_p Pointer to a dimensions struct"," * @param[in] page_p Pointer to a page struct"
+"q@	CHAR	0
+	f;a€ýalx€ýa
+|3,2,26,0,1,0,1654302803,"f;a€ýalx€ýa"
 "z	CHAR	0
 	QZQ€ýa€ýa€ýa€ýa
 |3,0,35,0,1,0,1630286931,"QZQ€ýa€ýa€ýa€ýa"
 "-	CHAR	0
-	&
-|3,0,36,0,1,0,1653009118,"&"
+	1
+|3,0,36,0,1,0,1654463392,"1"
 
 # Buffer list:
-%~/.gitignore	8	0
+%~/scripts/qvm	55	0
 
 # History of marks within files (newest to oldest):
 
-> ~/.gitignore
-	*	1653522268	0
-	"	8	0
-	^	16	8
-	.	16	7
-	+	19	6
-	+	15	7
-	+	20	0
-	+	17	0
-	+	15	0
-	+	22	0
-	+	14	0
-	+	9	10
-	+	22	6
-	+	1	0
-	+	16	7
-
-> ~/.xinitrc
-	*	1653084562	0
-	"	21	0
-	^	7	70
-	.	30	0
-	+	30	2
-	+	31	32
-	+	11	0
-	+	33	0
-	+	32	0
-	+	2	0
-	+	36	0
-	+	37	0
-	+	36	0
-	+	7	0
+> ~/scripts/qvm
+	*	1654464457	0
+	"	55	0
+	^	56	90
+	.	56	89
+	+	75	0
+	+	30	20
+	+	35	27
+	+	25	9
+	+	30	13
+	+	25	0
+	+	26	0
+	+	35	19
+	+	26	11
+	+	30	13
+	+	35	19
+	+	34	21
+	+	35	3
+	+	34	3
+	+	30	53
+	+	34	22
+	+	34	37
 	+	35	0
-	+	2	1
-	+	2	41
-	+	2	0
-	+	2	2
-	+	2	3
-	+	2	6
-	+	2	5
-	+	2	0
-	+	2	1
-	+	2	9
-	+	2	15
-	+	18	0
-	+	28	0
-	+	8	0
+	+	26	0
+	+	39	1
+	+	39	2
+	+	39	5
+	+	39	91
+	+	39	18
+	+	39	14
+	+	39	62
+	+	40	1
+	+	44	0
+	+	61	1
+	+	62	0
+	+	39	0
+	+	66	0
+	+	53	7
+	+	54	6
+	+	45	6
+	+	43	0
+	+	42	10
+	+	46	47
+	+	49	0
+	+	52	34
+	+	49	30
+	+	56	6
+	+	41	5
+	+	56	15
+	+	56	24
+	+	27	9
+	+	30	28
+	+	31	20
+	+	56	13
+	+	56	24
+	+	56	0
+	+	56	47
+	+	56	45
+	+	56	46
+	+	56	0
+	+	78	12
+	+	56	0
+	+	57	30
+	+	56	9
+	+	10	7
+	+	56	8
+	+	56	27
+	+	56	20
+	+	57	0
+	+	62	13
+	+	72	99
+	+	71	39
+	+	72	52
+	+	62	59
+	+	3	87
+	+	71	69
+	+	46	61
+	+	49	45
+	+	52	49
+	+	56	0
+	+	56	58
+	+	57	0
+	+	56	28
+	+	46	47
+	+	49	45
+	+	52	49
+	+	56	76
+	+	72	80
+	+	72	0
+	+	72	80
+	+	63	7
+	+	72	94
+	+	63	0
+	+	56	41
+	+	12	6
+	+	56	88
+	+	56	0
+	+	56	15
+	+	56	27
+	+	71	15
+	+	72	5
+	+	71	5
+	+	30	54
+	+	56	0
+	+	56	89
+
+> ~/scripts/file.log
+	*	1654464444	0
+	"	12	14
+
+> ~/scripts/bt
+	*	1654462574	0
+	"	9	0
+	^	19	40
+	.	9	0
 	+	9	0
-	+	2	0
-	+	9	0
-	+	8	25
-	+	9	10
-	+	1	0
-	+	33	19
-	+	30	33
-	+	29	3
-	+	30	21
-	+	7	69
-	+	30	0
 
-> ~/pywal-git/PKGBUILD
-	*	1653007663	0
-	"	19	66
-	^	19	67
-	.	19	66
-	+	20	67
-	+	19	66
-
-> ~/pywal/setup.py
-	*	1653007576	0
-	"	2	8
-
-> ~/out.log
-	*	1653007413	0
-	"	53	0
-
-> ~/debug
-	*	1653007353	0
+> ~/scripts/emoji
+	*	1654462395	0
 	"	1	0
 
 > ~/scripts/printctl
-	*	1652997402	0
-	"	7	36
-	^	6	8
-	.	6	8
-	+	11	50
-	+	11	0
-	+	10	19
-	+	10	6
-	+	11	46
-	+	4	0
-	+	10	27
-	+	13	43
-	+	13	0
-	+	13	2
-	+	13	3
-	+	13	13
-	+	11	76
-	+	12	16
-	+	13	0
-	+	5	0
-	+	9	0
-	+	13	0
-	+	6	8
-
-> ~/scripts/bt
-	*	1652997282	0
+	*	1654462389	0
 	"	1	0
 
-> ~/scripts/qvm
-	*	1652997278	0
-	"	8	0
-
 > ~/scripts/gotourl
-	*	1652997022	0
-	"	21	0
+	*	1654462385	0
+	"	1	0
+	^	8	14
+	.	5	0
+	+	8	13
+	+	5	0
+
+> ~/scripts/pullgit
+	*	1654462379	0
+	"	16	22
+
+> ~/scripts/yt-audio
+	*	1654462366	0
+	"	17	48
+
+> /usr/share/vim/vim82/doc/help.txt
+	*	1654457662	0
+	"	1	0
+
+> ~/qr
+	*	1654447828	0
+	"	1	0
diff --git a/scripts/qvm b/scripts/qvm
--- a/scripts/qvm
+++ b/scripts/qvm
@@ -8,6 +8,8 @@
 SELECTION=
 ARCH=
 MACHINE=
+LANG=en-us
+NCPUS=
 ISO_PATH="$HOME/devel/VMs/isos"
 
 # Functions
@@ -25,7 +27,7 @@ get_architecture()
    for PKG in $INSTALLED
    do
       i=$((i+1)) # POSIX compliant, unlike ((i++))
-      set -- "$@" $(echo $PKG | sed s/qemu-system-//) # POSIX compliant method of adding elements to an array
+      set -- "$@" "$(echo $PKG | sed s/qemu-system-//)" # POSIX compliant method of adding elements to an array
       echo "[$i] $PKG"
    done
    echo "Please select the target architecture: "; read -r SELECTION
@@ -51,7 +53,7 @@ select_machine()
       ;;
    esac
 
-   MACHINE=$(echo $CHOICES | awk '{if (NR>1) {print $1}}' | tr " " "\n" | dmenu -i -l 100 -p "Enter the desired machine")
+   MACHINE=$(echo "$CHOICES" | awk '{if (NR>1) {print $1}}' | tr " " "\n" | dmenu -i -l 50 -p "Enter the desired machine")
    echo "You selected $MACHINE"
 }
 
@@ -66,8 +68,8 @@ check_machine()
    echo "Would you like to select which machine to use (usually required for arm/aarch64)?"
    echo "[y/n]"
    read -r SELECTION
-   [ $SELECTION = y ] && select_machine && select_hardware_accelerator
-   [ $SELECTION = n ] && select_hardware_accelerator || echo "Invalid selection"; check_machine
+   [ "$SELECTION" = y ] && select_machine && select_hardware_accelerator
+   [ "$SELECTION" = n ] && select_hardware_accelerator || echo "Invalid selection"; check_machine
 }
 
 # Invoke functions
