This sucks

diff --git a/scripts/bt b/scripts/bt
--- a/scripts/bt
+++ b/scripts/bt
@@ -1,23 +1,41 @@
 #!/bin/sh
 #
-# Initialize bluetooth via bluetoothctl
+# Purpose: Connect headphones to bluetooth
+#
+# Dependencies: bluetoothctl, bluez5
 # 
 # If you consistently have troubles connecting, even after using bt off, you will
-# need to kill pulseaudio, start it, enter bluetoothctl manually, remove device,
-# power off, scan off and reset device list on headphones. Then try again
+# need to restart your audio daemon, enter bluetoothctl manually, remove device,
+# power off, scan off, and reset device list on headphones. Then try again
 
 SELECTION=$1
 MAC=28:11:A5:44:BE:B0
 
-function stereo {
-	echo "Please ensure headphones are already in pairing mode; otherwise stop this script, put them in pairing mode and try again..."
-	echo "Turning on headphones with stereo profile..."
+signal_handler() {
+   echo
+   PAIR_STAT=$(bluetoothctl info $MAC | sed '6q;d' | awk '{print $2}')
+   [ "$PAIR_STAT" = "yes" ] && echo "Successfully paired with $MAC!" || echo "Failed to pair with $MAC..."
+   kill -TERM -$$
+}
+
+turnon() {
+   trap signal_handler INT
+
+	echo "Please put headphones in pairing mode. Wait a second or two and then press Ctrl+C to pair."
+   echo "If this fails, turn headphones off and try again."
 	bluetoothctl power on
 	bluetoothctl scan on
 	bluetoothctl connect $MAC
+
+   for i in {1..100}
+   do
+      sleep 1 &
+   done   
+
+   wait
 }
 
-function turnoff {
+turnoff() {
 	bluetoothctl disconnect $MAC
 	bluetoothctl power off
 	bluetoothctl quit
@@ -25,9 +43,17 @@ function turnoff {
 }
 
 case $SELECTION in
-on) stereo;;
-off) turnoff;;
-*)
-	echo -e "\nHelp\non) Attempts a connection with Bose QC II. This means high quality audio with no mic\nsupport. Ensure that headphones are in pairing mode and press Ctrl+C after bluetoothctl has recognized the device.\n\noff) Disconnects from the target device and powers off bluetoothctl. Not required in most circumstances."
+on) 
+   turnon
+   ;;
+off) 
+   turnoff
+   ;;
+*) 
+   echo "Options:"
+   echo 
+   echo "    on) Attempts to connect with headphones. Headphones must be in pairing mode."
+   echo "    off) Terminates connection between headphones and bluetooth dongle."
+   echo
 	;;
 esac
