Updated/Added files

diff --git a/scripts/yt-audio b/scripts/yt-audio
--- a/scripts/yt-audio
+++ b/scripts/yt-audio
@@ -2,19 +2,21 @@
 #
 # Extract the best audio quality from a youtube video
 
+# TODO: noglob not working for some reason even though it works on CLI
+
 MUSIC_DIR=$HOME/music
 
-# Get last parameter (Posix compliant)
+# Get last parameter (POSIX compliant)
 for URL in $@; do :; done
 
 for ((i = 1; i <= $#; i++)); do
 	eval ARG=\$$i
 	case $ARG in
 		"-d")
-			echo "Enter the directory you'd like to place the file in (default is $(echo $MUSIC_DIR))"; read DIR 
-			echo "Enter the new name of the file (default is to keep file name unchanged)"; read NAME 
-			! [ -z $(echo $URL | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 $URL || (echo "Invalid URL" && exit 0)
-			FILE="$(echo $(yt-dlp --get-filename $URL) | sed 's/webm/opus/g')"
+			echo "Enter the directory you'd like to place the file in (default is $(echo $MUSIC_DIR))"; read DIR
+			echo "Enter the new name of the file (default is to keep file name unchanged)"; read NAME
+         ! [ -z $(echo "$URL" | grep "www.youtube.com") ] && noglob yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || (echo "Invalid URL" && exit 0)
+         FILE="$(echo $(noglob yt-dlp --get-filename "$URL") | sed 's/webm/opus/g')"
 			! [ -z $NAME ] && mv "$FILE" "$NAME" || NAME="$FILE"
 			[ -z $DIR ] && DIR="$MUSIC_DIR"
 			mv "$NAME" "$DIR"
@@ -28,7 +30,7 @@ for ((i = 1; i <= $#; i++)); do
 			exit 0
 			;;
 		*)
-			! [ -z $(echo $URL | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 $URL || echo "Invalid URL"
+			! [ -z $(echo "$URL" | grep "www.youtube.com") ] && noglob yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"
 			exit 0
 			;;
 	esac
