Added a few scripts

diff --git a/scripts/yt-audio b/scripts/yt-audio
--- a/scripts/yt-audio
+++ b/scripts/yt-audio
@@ -1,8 +1,9 @@
 #!/bin/sh
 #
 # Extract the best audio quality from a youtube video
-
-# TODO: noglob not working for some reason even though it works on CLI
+# NOTE: The URL must be surrounded in double quotes, otherwise your terminal will
+# interpret special characters such as '?' as a regex pattern
+# TODO: Replace echos with printf
 
 MUSIC_DIR=$HOME/music
 
@@ -15,22 +16,22 @@ for ((i = 1; i <= $#; i++)); do
 		"-d")
 			echo "Enter the directory you'd like to place the file in (default is $(echo $MUSIC_DIR))"; read DIR
 			echo "Enter the new name of the file (default is to keep file name unchanged)"; read NAME
-         ! [ -z $(echo "$URL" | grep "www.youtube.com") ] && noglob yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || (echo "Invalid URL" && exit 0)
-         FILE="$(echo $(noglob yt-dlp --get-filename "$URL") | sed 's/webm/opus/g')"
-			! [ -z $NAME ] && mv "$FILE" "$NAME" || NAME="$FILE"
+         ! [ -z $(echo "$URL" | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || (echo "Invalid URL" && exit 0)
+         FILE="$(echo $(yt-dlp --get-filename "$URL") | sed 's/webm/opus/g')"
+			! [ -z $NAME ] && mv "$FILE" "$NAME.opus" || NAME="$FILE"
 			[ -z $DIR ] && DIR="$MUSIC_DIR"
-			mv "$NAME" "$DIR"
+			mv "$NAME.opus" "$DIR"
 			exit 0
 			;;
 		"-h")
-			echo "Usage: yt-dlaudio [Options...] <URL>"
+			echo "Usage: yt-dlaudio [Options...] \"<URL>\""
 			echo "Options:"
 			echo "-d Specify output directory"
 			echo "-h Help menu"
 			exit 0
 			;;
 		*)
-			! [ -z $(echo "$URL" | grep "www.youtube.com") ] && noglob yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"
+			! [ -z $(echo "$URL" | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"
 			exit 0
 			;;
 	esac
