Cleanup

diff --git a/scripts/yt-audio b/scripts/yt-audio
--- a/scripts/yt-audio
+++ b/scripts/yt-audio
@@ -3,36 +3,35 @@
 # Extract the best audio quality from a youtube video
 # NOTE: The URL must be surrounded in double quotes, otherwise your terminal will
 # interpret special characters such as '?' as a regex pattern
-# TODO: Replace echos with printf
 
 MUSIC_DIR=$HOME/music
 
 # Get last parameter (POSIX compliant)
-for URL in $@; do :; done
+for URL in "$@"; do :; done
 
 for ((i = 1; i <= $#; i++)); do
-	eval ARG=\$$i
+	eval ARG=\$"$i"
 	case $ARG in
 		"-d")
-			echo "Enter the directory you'd like to place the file in (default is $(echo $MUSIC_DIR))"; read DIR
-			echo "Enter the new name of the file (default is to keep file name unchanged)"; read NAME
-         ! [ -z $(echo "$URL" | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || (echo "Invalid URL" && exit 0)
-         FILE="$(echo $(yt-dlp --get-filename "$URL") | sed 's/webm/opus/g')"
-			! [ -z $NAME ] && mv "$FILE" "$NAME.opus" || NAME="$FILE"
-			[ -z $DIR ] && DIR="$MUSIC_DIR"
+			printf "Enter the directory you'd like to place the file in (default is %s)\n" "$MUSIC_DIR"; read -r DIR
+			printf "Enter the new name of the file (default is to keep file name unchanged)\n"; read -r NAME
+         [ "$(grep -q "www.youtube.com")" ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"; exit 0
+         FILE="$(yt-dlp --get-filename "$URL" | sed 's/webm/opus/g')"
+			[ -n "$NAME" ] && mv "$FILE" "$NAME.opus" || NAME="$FILE"
+			[ -z "$DIR" ] && DIR="$MUSIC_DIR"
 			mv "$NAME.opus" "$DIR"
 			exit 0
 			;;
 		"-h")
-			echo "Usage: yt-dlaudio [Options...] \"<URL>\""
-			echo "Options:"
-			echo "-d Specify output directory"
-			echo "-h Help menu"
+			print "Usage: yt-dlaudio [Options...] \"<URL>\"\n" \
+			"Options:\n" \
+			"-d Specify output directory\n" \
+			"-h Help menu\n"
 			exit 0
 			;;
 		*)
          # Use --force-ipv4 because ipv6 is extremely slow
-			! [ -z $(echo "$URL" | grep "www.youtube.com") ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"
+			[ "$(grep -q "www.youtube.com")" ] && yt-dlp -f bestaudio --extract-audio --force-ipv4 "$URL" || echo "Invalid URL"
 			exit 0
 			;;
 	esac
